import{S as v,i as h,a as F}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const H="https://pixabay.com/api/",g=document.querySelector(".gallery"),p=document.querySelector(".search-form"),i=document.querySelector(".loader"),d=document.querySelector(".load-more-button"),u=new v(".gallery-link");let n=1,y="";p.addEventListener("submit",async function(e){e.preventDefault();const r=e.target.elements.query.value.trim();if(r!==""){y=r,n=1,g.innerHTML="",i.style.display="block";try{const{hits:o,totalHits:a}=await f(y,n);if(Array.isArray(o)&&o.length>0){const t=o.map(m).join("");g.innerHTML=t,M(`Was found: ${a} images`),u.refresh(),b()}else l("Вибачте, немає зображень, які відповідають вашому пошуковому запиту. Будь ласка спробуйте ще раз!")}catch(o){l(`Error fetching images: ${o.message}`)}finally{p.reset(),i.style.display="none"}}});d.addEventListener("click",async function(){n++,i.style.display="block";try{const{hits:e}=await f(y,n);if(Array.isArray(e)&&e.length>0){const r=e.map(m).join("");g.innerHTML+=r,u.refresh()}else w()}catch(e){l(`Error fetching more images: ${e.message}`)}finally{i.style.display="none"}});const L={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function l(e){h.show({message:e,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...L})}function M(e){h.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...L})}async function f(e,r){const o={key:"42198701-b9a5fa575f7b9ea832aebf9b8",image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,q:e,page:r};try{const a=await F.get(H,{params:o});if(!a.data)throw new Error("No data found");return a.data}catch(a){throw new Error(`Error fetching images: ${a.message}`)}}function m({largeImageURL:e,tags:r,webformatURL:o,likes:a,views:t,comments:s,downloads:c}){return`
  <a href="${e}" class="gallery-link">
     <figure>
      <img src="${o}" alt="${r}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${t}</span></div>
        <div class="image-item">Comments <span class="image-elem">${s}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${c}</span></div>
      </figcaption>
     </figure>
  </a>
`}function b(){d.style.display="block"}function w(){d.style.display="none"}const C="Вибачте, але ви досягли кінця результатів пошуку.";function E(e){n*15>=e?(w(),l(C)):b()}d.addEventListener("click",async function(){n++,i.style.display="block";try{const{hits:e,totalHits:r}=await f(y,n);if(Array.isArray(e)&&e.length>0){const o=e.map(m).join("");g.innerHTML+=o,u.refresh()}else E(r)}catch(e){l(`Error fetching more images: ${e.message}`)}finally{i.style.display="none"}});d.addEventListener("click",async function(){n++,i.style.display="block";try{const{hits:e,totalHits:r}=await f(y,n);if(Array.isArray(e)&&e.length>0){const o=e.map(m).join("");g.innerHTML+=o,u.refresh(),S()}else E(r)}catch(e){l(`Error fetching more images: ${e.message}`)}finally{i.style.display="none"}});function S(){const r=document.querySelector(".gallery-link").getBoundingClientRect().height*3;window.scrollBy({top:r,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
