import{S as w,i as f,a as S}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const C="https://pixabay.com/api/",u=document.querySelector(".gallery"),m=document.querySelector(".search-form"),l=document.querySelector(".loader"),d=document.querySelector(".load-more-button"),y=new w(".gallery-link");let c=1,g="";m.addEventListener("submit",async function(e){e.preventDefault();const r=e.target.elements.query.value.trim();if(r!==""){g=r,u.innerHTML="",l.style.display="block";try{const{hits:o,totalHits:a}=await h(g,c);if(Array.isArray(o)&&o.length>0){const t=o.map(b).join("");u.innerHTML=t,E(`Was found: ${a} images`),y.refresh(),L()}else i("Sorry, there are no images matching your search query. Please try again!")}catch(o){i(`Error fetching images: ${o.message}`)}finally{m.reset(),l.style.display="none"}}});const p={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function i(e){f.show({message:e,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...p})}function E(e){f.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...p})}async function h(e,r){const o={key:"42198701-b9a5fa575f7b9ea832aebf9b8",image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,q:e,page:r};try{const a=await S.get(C,{params:o});if(!a.data)throw new Error("No data found");return a.data}catch(a){throw new Error(`Error fetching images: ${a.message}`)}}function b({largeImageURL:e,tags:r,webformatURL:o,likes:a,views:t,comments:s,downloads:n}){return`
  <a href="${e}" class="gallery-link">
     <figure>
      <img src="${o}" alt="${r}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${t}</span></div>
        <div class="image-item">Comments <span class="image-elem">${s}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${n}</span></div>
      </figcaption>
     </figure>
  </a>
`}function L(){d.style.display="block"}function F(){d.style.display="none"}const v="Sorry, but you have reached the end of the search results.";function M(e){const r=Math.ceil(e/15);c>=r?(F(),i(v)):L()}d.addEventListener("click",async function(){c+=1,l.style.display="block";try{const{hits:e,totalHits:r}=await h(g,c);if(Array.isArray(e)&&e.length>0){const o=e.map(b).join("");u.innerHTML+=o,y.refresh(),H(),M(r)}else F(),i(v)}catch(e){i(`Error fetching more images: ${e.message}`)}finally{l.style.display="none"}});function H(){const r=document.querySelector(".gallery-link").getBoundingClientRect().height*2;window.scrollBy({top:r,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
