import{S,i as y,a as C}from"./assets/vendor-b42c18af.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const M="https://pixabay.com/api/",g=document.querySelector(".gallery"),m=document.querySelector(".search-form"),c=document.querySelector(".loader"),u=document.querySelector(".load-more-button"),f=new S(".gallery-link");let i=1,d="";m.addEventListener("submit",async function(e){e.preventDefault();const o=e.target.elements.query.value.trim();if(o!==""){u.style.display="none",i=1,d=o,g.innerHTML="",c.style.display="block";try{const{hits:r,totalHits:a}=await h(d,i);if(Array.isArray(r)&&r.length>0){const t=r.map(b).join("");g.innerHTML=t,w(`Was found: ${a} images`),f.refresh(),L()}else l("Sorry, there are no images matching your search query. Please try again!")}catch(r){l(`Error fetching images: ${r.message}`)}finally{m.reset(),c.style.display="none"}}});const p={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function l(e){y.show({message:e,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...p})}function w(e){y.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...p})}async function h(e,o){const r={key:"42198701-b9a5fa575f7b9ea832aebf9b8",image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,q:e,page:o};return(await C.get(M,{params:r})).data}function b({largeImageURL:e,tags:o,webformatURL:r,likes:a,views:t,comments:s,downloads:n}){return`
  <a href="${e}" class="gallery-link">
     <figure>
      <img src="${r}" alt="${o}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${t}</span></div>
        <div class="image-item">Comments <span class="image-elem">${s}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${n}</span></div>
      </figcaption>
     </figure>
  </a>
`}function L(){u.style.display="block"}function F(){u.style.display="none"}const v="Sorry, but you have reached the end of the search results.";function H(e){const o=Math.ceil(e/15);i>=o?(F(),l(v)):L()}u.addEventListener("click",async function(){i+=1,c.style.display="block";try{const{hits:e,totalHits:o}=await h(d,i);if(Array.isArray(e)&&e.length>0){const r=e.map(b).join("");g.insertAdjacentHTML("beforeend",r),f.refresh(),E(),H(o)}else F(),l(v)}catch(e){l(`Error fetching more images: ${e.message}`)}finally{c.style.display="none"}});function E(){const o=document.querySelector(".gallery-link").getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
